kind: CronJob
apiVersion: batch/v1
metadata:
  name: ora2pg-cas
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
            volumes:
              - name: ora2pg-vol
                persistentVolumeClaim:
                  claimName: ora2pg-cas
              - name: ssh-config
                configMap:
                  name: ssh-config
                  defaultMode: 420
              - name: ssh-key
                secret:
                  secretName: cas-ssh
                  items:
                  - key: known_hosts
                    path: known_hosts
                    readOnly: true
              - name: ssh-rsa
                secret:
                  secretName: cas-ssh-key
                  items:
                  - key: id_rsa
                    path: id_rsa
                    readOnly: true
            containers:
              - resources:
                  limits:
                    cpu: 250m
                    memory: 1Gi
                  requests:
                    cpu: 50m
                    memory: 256Mi
                terminationMessagePath: /dev/termination-log
                name: cas-puller
                imagePullPolicy: Always
                volumeMounts:
                  - name: ora2pg-vol
                    mountPath: /data
                  - name: ssh-config
                    readOnly: true
                    mountPath: /.ssh/config
                    subPath: config
                  - name: ssh-key
                    mountPath: /.ssh/known_hosts
                    subPath: known_hosts
                    readOnly: true
                  - name: ssh-rsa
                    mountPath: /.ssh/rsa
                    readOnly: true
                terminationMessagePolicy: File
                image: image-registry.openshift-image-registry.svc:5000/78c88a-tools/cas-puller:latest
                env:
                  - name: NETTLE_IP
                    valueFrom:
                      secretKeyRef:
                        name: ora2pg-cas
                        key: NETTLE_IP
                  - name: ORA_CONF_UPDATE
                    valueFrom:
                      secretKeyRef:
                        name: ora2pg-cas
                        key: ORA_CONF_UPDATE
                  - name: ORA_CONF_INSERT
                    valueFrom:
                      secretKeyRef:
                        name: ora2pg-cas
                        key: ORA_CONF_INSERT
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
